services:
    app:
        image: ${APP_NAME:-robmeijer-me}-app:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: local
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"
            - "${HTTP3_PORT:-443}:443/udp"
