app = 'robmeijer-me'
primary_region = 'lhr'

[build]
dockerfile = 'docker/Dockerfile'
build-target = 'app'

[deploy]
strategy = 'rolling'

[env]
SERVER_NAME = ':80'

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = '512mb'
processes = ['app']
